version: '3'

networks:
  app-network:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: app-server
    env_file: .env.local
    tty: true
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    ports:
      - "${DOCKER_PORT:-3001}:${PORT:-3000}"
      - "${DEBUG_PORT:-9229}:9229"
    environment:
      - NODE_ENV=${NODE_ENV:-local}

  postgres:
    image: bitnami/postgresql:15
    container_name: app-postgres
    env_file: .env.local
    tty: true
    volumes:
      - app-postgres:/bitnami/postgresql
    networks:
      - app-network
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME:-root}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRESQL_DATABASE=${DB_NAME:-development}

  redis:
    image: bitnami/redis:latest
    container_name: app-redis
    env_file: .env.local
    tty: true
    networks:
      - app-network
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - ALLOW_EMPTY_PASSWORD=no

volumes:
  app-postgres:
