FROM node:20-alpine

# create node user
ENV USER=node

# create workdir
ENV WORKDIR=/home/${USER}/app
WORKDIR ${WORKDIR}

# copy and install node packages
COPY --chown=${user}:${user} package*.json ./
RUN npm install --ignore-scripts
COPY --chown=${USER}:${USER} . .

# expose port
ENV PORT=${PORT:-3000}
EXPOSE ${PORT}

# run as node user
USER ${USER}

# run application
CMD ["npm", "run", "dev:local"]
