version: '3'

networks:
  app.network:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: app.server
    working_dir: /home/node
    env_file: .env.local
    tty: true
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/home/node
      - /home/node/node_modules
    networks:
      - app.network
    ports:
      - "${DOCKER_PORT:-3301}:${PORT:-3333}"
      - "${DEBUG_PORT:-9229}:9229"
    environment:
      - NODE_ENV=${NODE_ENV:-local}

  postgres:
    image: bitnami/postgresql:15
    container_name: app.postgres
    tty: true
    env_file: .env.local
    volumes:
      - app.volume.postgres:/bitnami/postgresql
    networks:
      - app.network
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME:-root}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-root}
      - POSTGRESQL_DATABASE=${DB_NAME:-development}

  redis:
    image: bitnami/redis:latest
    container_name: app.redis
    platform: linux/amd64
    tty: true
    env_file: .env.local
    volumes:
      - app.volume.redis:/bitnami/redis/data
    networks:
      - app.network
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - ALLOW_EMPTY_PASSWORD=no

volumes:
  app.volume.redis:
  app.volume.postgres:
