apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: node-api
  labels:
    app: node-api
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: node-api
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - name: node-api
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: node-api
            - secretRef:
                name: api
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 200m
