apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-api-hpa
  namespace: node-api
spec:
  scaleTargetRef:
    name: node-api
    apiVersion: apps/v1
    kind: Deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 160
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 160
