apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - name: api
      targetPort: 3000
      protocol: TCP
      port: 80
