name: Check TS and Run Tests

concurrency:
  group: ${{ github.workflow }}:${{ github.ref }}
  cancel-in-progress: true

on:
  - push
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run check-ts

      - name: Run Tests
        env:
          TZ: 'UTC'
          REDIS_PORT: '6379'
          CHECK_ENVFILE: 'false'
          REDIS_HOST: 'localhost'
        run: npm run test:all
