name: Check TS

concurrency:
  group: ${{ github.workflow }}:check-ts:${{ github.ref }}
  cancel-in-progress: true

env:
  REDIS_PORT: '6379'
  CHECK_ENVFILE: 'false'
  REDIS_HOST: 'localhost'
  REDACTED_KEYS: 'password,testObject'
  TZ_UTC: 'UTC'
  TZ_BRL: 'America/Sao_Paulo'
  TZ: 'UTC'

on:
  push:
    paths:
      - '.github/workflows/check-ts.yml'
      - 'src/**/*.ts'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: Check TS
        run: npm run check-ts:ci

      - name: Run Tests
        run: npm run test:all
