name: Test

concurrency:
  group: ${{ github.workflow }}:test:${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.ts'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: Check TS
        run: npm run check-ts:ci

      - name: Run Unit Tests
        run: npm run test:unit:all

      - name: Run Integration Tests
        run: npm run test:e2e:all
